//*
// # File Get Contents
// Messages for a query to retrieve the content of a file in the
// Hedera File Service (HFS).
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v4.25.3
// source: file_get_contents.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// A query request to the Hedera File Service (HFS) for file content.<br/>
// This query requests the content of a file, but none of the information
// _about_ a file. A client should submit a `fileGetInfo` query to view
// information about a file.<br/>
// File content may also be available from a block node or mirror node,
// generally at lower cost.
type FileGetContentsQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// Standard information sent with every query operation.<br/>
	// This includes the signed payment and what kind of response is requested
	// (cost, state proof, both, or neither).
	Header *QueryHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// *
	// A file identifier.
	// <p>
	// This MUST be the identifier of a file that exists in HFS.<br/>
	// This value SHALL identify the file to be queried.
	FileID *FileID `protobuf:"bytes,2,opt,name=fileID,proto3" json:"fileID,omitempty"`
}

func (x *FileGetContentsQuery) Reset() {
	*x = FileGetContentsQuery{}
	mi := &file_file_get_contents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileGetContentsQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileGetContentsQuery) ProtoMessage() {}

func (x *FileGetContentsQuery) ProtoReflect() protoreflect.Message {
	mi := &file_file_get_contents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileGetContentsQuery.ProtoReflect.Descriptor instead.
func (*FileGetContentsQuery) Descriptor() ([]byte, []int) {
	return file_file_get_contents_proto_rawDescGZIP(), []int{0}
}

func (x *FileGetContentsQuery) GetHeader() *QueryHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *FileGetContentsQuery) GetFileID() *FileID {
	if x != nil {
		return x.FileID
	}
	return nil
}

// *
// A response to a query for the content of a file in the
// Hedera File Service (HFS).
//
// This message SHALL contain the full content of the requested file, but
// SHALL NOT contain any metadata.
type FileGetContentsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// The standard response information for queries.<br/>
	// This includes the values requested in the `QueryHeader`
	// (cost, state proof, both, or neither).
	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// *
	// A combination of File identifier and content bytes.
	// <p>
	// This SHALL NOT be set if the file does not exist.<br/>
	// The network MAY generate a state proof for this field.
	FileContents *FileGetContentsResponse_FileContents `protobuf:"bytes,2,opt,name=fileContents,proto3" json:"fileContents,omitempty"`
}

func (x *FileGetContentsResponse) Reset() {
	*x = FileGetContentsResponse{}
	mi := &file_file_get_contents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileGetContentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileGetContentsResponse) ProtoMessage() {}

func (x *FileGetContentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_file_get_contents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileGetContentsResponse.ProtoReflect.Descriptor instead.
func (*FileGetContentsResponse) Descriptor() ([]byte, []int) {
	return file_file_get_contents_proto_rawDescGZIP(), []int{1}
}

func (x *FileGetContentsResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *FileGetContentsResponse) GetFileContents() *FileGetContentsResponse_FileContents {
	if x != nil {
		return x.FileContents
	}
	return nil
}

type FileGetContentsResponse_FileContents struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// A file identifier.
	// <p>
	// This SHALL be the identifier of a file that exists in HFS.<br/>
	// This value SHALL identify the file that was queried.
	FileID *FileID `protobuf:"bytes,1,opt,name=fileID,proto3" json:"fileID,omitempty"`
	// *
	// A byte array of file content.
	// <p>
	// This SHALL contain the full content of the requested file.<br/>
	// This SHALL be empty if, and only if, the file content is empty.
	Contents []byte `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
}

func (x *FileGetContentsResponse_FileContents) Reset() {
	*x = FileGetContentsResponse_FileContents{}
	mi := &file_file_get_contents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileGetContentsResponse_FileContents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileGetContentsResponse_FileContents) ProtoMessage() {}

func (x *FileGetContentsResponse_FileContents) ProtoReflect() protoreflect.Message {
	mi := &file_file_get_contents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileGetContentsResponse_FileContents.ProtoReflect.Descriptor instead.
func (*FileGetContentsResponse_FileContents) Descriptor() ([]byte, []int) {
	return file_file_get_contents_proto_rawDescGZIP(), []int{1, 0}
}

func (x *FileGetContentsResponse_FileContents) GetFileID() *FileID {
	if x != nil {
		return x.FileID
	}
	return nil
}

func (x *FileGetContentsResponse_FileContents) GetContents() []byte {
	if x != nil {
		return x.Contents
	}
	return nil
}

var File_file_get_contents_proto protoreflect.FileDescriptor

var file_file_get_contents_proto_rawDesc = []byte{
	0x0a, 0x17, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x11, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x69,
	0x0a, 0x14, 0x46, 0x69, 0x6c, 0x65, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x2a, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x25, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x49,
	0x44, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x22, 0xec, 0x01, 0x0a, 0x17, 0x46, 0x69,
	0x6c, 0x65, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x4f, 0x0a, 0x0c, 0x66, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x0c, 0x66, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x51, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x49, 0x44, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x42, 0x26, 0x0a, 0x22, 0x63, 0x6f, 0x6d, 0x2e,
	0x68, 0x65, 0x64, 0x65, 0x72, 0x61, 0x68, 0x61, 0x73, 0x68, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x6a, 0x61, 0x76, 0x61, 0x50, 0x01,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_file_get_contents_proto_rawDescOnce sync.Once
	file_file_get_contents_proto_rawDescData = file_file_get_contents_proto_rawDesc
)

func file_file_get_contents_proto_rawDescGZIP() []byte {
	file_file_get_contents_proto_rawDescOnce.Do(func() {
		file_file_get_contents_proto_rawDescData = protoimpl.X.CompressGZIP(file_file_get_contents_proto_rawDescData)
	})
	return file_file_get_contents_proto_rawDescData
}

var file_file_get_contents_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_file_get_contents_proto_goTypes = []any{
	(*FileGetContentsQuery)(nil),                 // 0: proto.FileGetContentsQuery
	(*FileGetContentsResponse)(nil),              // 1: proto.FileGetContentsResponse
	(*FileGetContentsResponse_FileContents)(nil), // 2: proto.FileGetContentsResponse.FileContents
	(*QueryHeader)(nil),                          // 3: proto.QueryHeader
	(*FileID)(nil),                               // 4: proto.FileID
	(*ResponseHeader)(nil),                       // 5: proto.ResponseHeader
}
var file_file_get_contents_proto_depIdxs = []int32{
	3, // 0: proto.FileGetContentsQuery.header:type_name -> proto.QueryHeader
	4, // 1: proto.FileGetContentsQuery.fileID:type_name -> proto.FileID
	5, // 2: proto.FileGetContentsResponse.header:type_name -> proto.ResponseHeader
	2, // 3: proto.FileGetContentsResponse.fileContents:type_name -> proto.FileGetContentsResponse.FileContents
	4, // 4: proto.FileGetContentsResponse.FileContents.fileID:type_name -> proto.FileID
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_file_get_contents_proto_init() }
func file_file_get_contents_proto_init() {
	if File_file_get_contents_proto != nil {
		return
	}
	file_basic_types_proto_init()
	file_query_header_proto_init()
	file_response_header_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_file_get_contents_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_file_get_contents_proto_goTypes,
		DependencyIndexes: file_file_get_contents_proto_depIdxs,
		MessageInfos:      file_file_get_contents_proto_msgTypes,
	}.Build()
	File_file_get_contents_proto = out.File
	file_file_get_contents_proto_rawDesc = nil
	file_file_get_contents_proto_goTypes = nil
	file_file_get_contents_proto_depIdxs = nil
}
