//*
// # Current and next TSS encryption keys
//
// ### Keywords
// The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
// "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
// document are to be interpreted as described in
// [RFC2119](https://www.ietf.org/rfc/rfc2119) and clarified in
// [RFC8174](https://www.ietf.org/rfc/rfc8174).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v4.25.3
// source: tss_encryption_keys.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// A message containing a node's current and next TSS encryption keys, where
// the next key (if present) will be switched to the node's current key during
// the first transaction at the beginning of a staking period.<br/>
type TssEncryptionKeys struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// *
	// If non-empty, a node's current TSS encryption key.
	CurrentEncryptionKey []byte `protobuf:"bytes,1,opt,name=current_encryption_key,json=currentEncryptionKey,proto3" json:"current_encryption_key,omitempty"`
	// *
	// If non-empty, the same node's next TSS encryption key.
	NextEncryptionKey []byte `protobuf:"bytes,2,opt,name=next_encryption_key,json=nextEncryptionKey,proto3" json:"next_encryption_key,omitempty"`
}

func (x *TssEncryptionKeys) Reset() {
	*x = TssEncryptionKeys{}
	mi := &file_tss_encryption_keys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TssEncryptionKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TssEncryptionKeys) ProtoMessage() {}

func (x *TssEncryptionKeys) ProtoReflect() protoreflect.Message {
	mi := &file_tss_encryption_keys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TssEncryptionKeys.ProtoReflect.Descriptor instead.
func (*TssEncryptionKeys) Descriptor() ([]byte, []int) {
	return file_tss_encryption_keys_proto_rawDescGZIP(), []int{0}
}

func (x *TssEncryptionKeys) GetCurrentEncryptionKey() []byte {
	if x != nil {
		return x.CurrentEncryptionKey
	}
	return nil
}

func (x *TssEncryptionKeys) GetNextEncryptionKey() []byte {
	if x != nil {
		return x.NextEncryptionKey
	}
	return nil
}

var File_tss_encryption_keys_proto protoreflect.FileDescriptor

var file_tss_encryption_keys_proto_rawDesc = []byte{
	0x0a, 0x19, 0x74, 0x73, 0x73, 0x5f, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x6b, 0x65, 0x79, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x63, 0x6f, 0x6d,
	0x2e, 0x68, 0x65, 0x64, 0x65, 0x72, 0x61, 0x2e, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x64,
	0x65, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x74, 0x73, 0x73, 0x22, 0x79, 0x0a, 0x11, 0x54,
	0x73, 0x73, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x73,
	0x12, 0x34, 0x0a, 0x16, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x65, 0x6e, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x14, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x12, 0x2e, 0x0a, 0x13, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x65,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x11, 0x6e, 0x65, 0x78, 0x74, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x42, 0x29, 0x0a, 0x25, 0x63, 0x6f, 0x6d, 0x2e, 0x68, 0x65,
	0x64, 0x65, 0x72, 0x61, 0x2e, 0x68, 0x61, 0x70, 0x69, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x2e, 0x74, 0x73, 0x73, 0x2e, 0x6c, 0x65, 0x67, 0x61, 0x63, 0x79, 0x50,
	0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tss_encryption_keys_proto_rawDescOnce sync.Once
	file_tss_encryption_keys_proto_rawDescData = file_tss_encryption_keys_proto_rawDesc
)

func file_tss_encryption_keys_proto_rawDescGZIP() []byte {
	file_tss_encryption_keys_proto_rawDescOnce.Do(func() {
		file_tss_encryption_keys_proto_rawDescData = protoimpl.X.CompressGZIP(file_tss_encryption_keys_proto_rawDescData)
	})
	return file_tss_encryption_keys_proto_rawDescData
}

var file_tss_encryption_keys_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tss_encryption_keys_proto_goTypes = []any{
	(*TssEncryptionKeys)(nil), // 0: com.hedera.hapi.node.state.tss.TssEncryptionKeys
}
var file_tss_encryption_keys_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tss_encryption_keys_proto_init() }
func file_tss_encryption_keys_proto_init() {
	if File_tss_encryption_keys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tss_encryption_keys_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tss_encryption_keys_proto_goTypes,
		DependencyIndexes: file_tss_encryption_keys_proto_depIdxs,
		MessageInfos:      file_tss_encryption_keys_proto_msgTypes,
	}.Build()
	File_tss_encryption_keys_proto = out.File
	file_tss_encryption_keys_proto_rawDesc = nil
	file_tss_encryption_keys_proto_goTypes = nil
	file_tss_encryption_keys_proto_depIdxs = nil
}
