version: "3"

tasks:
    update-addressbook:
        cmds:
            - go test ./sdk -tags="all" -v -run TestIntegrationAddressBookQueryUpdateAll

    run-examples:
        cmds:
            - |
              for example in examples/*; do
                 dir_name=$(basename "$example")
                  # Skip the consensus_pub_sub_chunked directory
                  if [ "$dir_name" == "consensus_pub_sub_chunked" ] || [ "$dir_name" == "initialize-client-with-mirror-node-adress-book" ]; then
                      echo "Skipping $example"
                      continue
                  fi
                  if [ -d "$example" ]; then

                      pushd "$example" > /dev/null
                      if [ -f main.go ]; then
                          echo "Running $example/main.go"
                          env OPERATOR_KEY="9a07bbdbb62e24686d2a4259dc88e38438e2c7a1ba167b147ad30ac540b0a3cd" OPERATOR_ID="0.0.1031" HEDERA_NETWORK="localhost" go run main.go
                      fi
                      popd > /dev/null
                  fi
              done

